version: "3.8"
services:
  ordemflow:
    image: postgres:16-alpine
    container_name: ordemflow
    environment:
      POSTGRES_DB: ordemflow_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
