spring:
  application:
    name: ordemFlow


  datasource:
    url: jdbc:postgresql://localhost:5436/ordemflow_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update



  flyway:
    enabled: true